# from config_local import JIRA_USERNAME,JIRA_API_KEY

# JIRA_USERNAME=JIRA_USERNAME
# JIRA_API_KEY=JIRA_API_KEY

import os

JIRA_USERNAME = os.getenv("JIRA_USERNAME")
JIRA_API_KEY = os.getenv("JIRA_API_KEY")

