[project]
name = "mbk-tool-service-render"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.116.1",
    "fastmcp>=2.10.5",
    "starlette>=0.47.1",
]
